fix(FEC-11288): define product version by core components
kaltura/server pull request #10802
Opened 2021-05-31 13:26 UTC by Yuvalke

2021-05-31 14:02 UTC, yairans requested changes

2021-05-31 14:18 UTC, Yuvalke commented on alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
> +			list($latestVersionMap, $latestProductVersion, $corePackages) = $this->getConfigByVersion("latest");
why? I thought to take the latest only, it's our stable package config.

2021-05-31 14:26 UTC, yairans commented on alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
> +			list($latestVersionMap, $latestProductVersion, $corePackages) = $this->getConfigByVersion("latest");
don't we report the product version on beta and canary?

2021-05-31 14:27 UTC, yairans commented on alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
> +			list($latestVersionMap, $latestProductVersion, $corePackages) = $this->getConfigByVersion("latest");
ignore. you are right

2021-05-31 14:29 UTC, yairans approved these changes

2021-06-15 07:41 UTC, MosheMaorKaltura commented
reviewed, please make sure change the base to 17.4

2021-06-27 07:28 UTC, yairans commented
@Yuvalke change the base to Quasar-17.5.0

2021-06-28 07:31 UTC, merged