fix(FEC-10994): remove uiconf specific for kaltura player data
kaltura/server pull request #10800
Opened 2021-05-31 09:47 UTC by Yuvalke

2021-05-31 12:29 UTC, yairans approved these changes

2021-06-02 04:06 UTC, OrenMe approved these changes

2021-06-27 07:26 UTC, yairans requested changes

2021-06-27 07:26 UTC, yairans commented on alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
> +	const NO_UICONF_FOR_KALTURA_DATA = '1.8.0';
```suggestion
	const NO_UICONF_FOR_KALTURA_DATA = '1.9.0';
```

2021-06-27 07:26 UTC, yairans commented on alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
> +		// For player latest/beta/canary or >= 1.8.0
```suggestion
		// For player latest/beta/canary or >= 1.9.0
```

2021-06-27 07:27 UTC, yairans commented on alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
> +		// For player latest/beta/canary or >= 1.8.0
@Yuvalke change the base to Quasar-17.5.0

2021-06-30 09:31 UTC, yairans requested changes

2021-06-30 09:31 UTC, yairans commented on alpha/apps/kaltura/modules/extwidget/actions/embedPlaykitJsAction.class.php
> +		// For player latest/beta/canary or >= 1.9.0
remove comment

2021-06-30 09:31 UTC, yairans approved these changes

2021-06-30 14:35 UTC, merged