ONPREM-448: Adjust LiveEntry::getStreamName() to use a switch statement based on the value of $liveBackend
kaltura/server pull request #12752
Opened 2024-06-14 19:05 UTC by navarro967

This pull request adjusts the `LiveEntry::getStreamName()` method to use a switch statement based on the value of the `$liveBackend` variable. This allows for different behavior depending on the value of `$liveBackend`, specifically for the `LIVE_BACKEND_WOWZA` and `LIVE_BACKEND_LIVE_NG` cases. This change improves the flexibility and maintainability of the code.

2024-06-26 08:53 UTC, david-winder-kaltura commented
I think better will be something like this:

public function getStreamName ()
    {
        $defaultValue = '%i';
        
        $conf = $this->getPartner()->getLiveStreamBroadcastUrlConfigurations(kDataCenterMgr::getCurrentDcId());
        if (isset($conf['stream_name_template']))
        {
            $defaultValue = str_replace('@ENTRY_ID@', $this->getId(), $conf['stream_name_template']);
        }
        
        return $this->getFromCustomData( "streamName", null, $defaultValue);
    }
    
    and then in the onprem configuration we can set 
    stream_name_template = @ENTRY_ID@_%i

2024-06-26 14:31 UTC, navarro967 commented
@david-winder-kaltura, I see your reasoning for this however will we still be able to configure this platform-wide as well? Configuring individual partners would be less than ideal for the intended use cases.

2024-06-27 07:27 UTC, amiras89 commented
the function getLiveStreamBroadcastUrlConfigurations() will take both 'broadcast' map and 'live_stream_broadcast_url_configurations' config from partner.
any value for the same key in 'live_stream_broadcast_url_configurations' will override the system level broadcast.ini

it allows to set 'stream_name_template' in broadcast.ini for a system wide settings
and, if needed, override it by placing it under 'live_stream_broadcast_url_configurations' of partner.

@navarro967 @david-winder-kaltura

2024-06-27 09:26 UTC, yossipapi requested changes

2024-06-27 09:26 UTC, yossipapi commented on alpha/lib/model/LiveEntry.php
> +	const LIVE_BACKEND_WOWZA = 0;
Why not use string constants like "wowze" & "liveNG" this way you won't have to crosscheck config value 0 to the class to see what it is.

2024-07-01 19:14 UTC, navarro967 commented
Params changed to fit David and Yossi's concerns:

broadcast.ini:
`stream_name_template = {entryId}_%i`

result:
![image](https://github.com/kaltura/server/assets/28518119/cfd602fc-a4e3-4d4b-8148-50de0a5cad62)

2024-07-01 19:15 UTC, navarro967 commented
@yossipapi @amiras89 @david-winder-kaltura, please check

2024-07-03 16:52 UTC, david-winder-kaltura approved these changes

2024-07-03 16:53 UTC, david-winder-kaltura commented
Please make sure to run full live QA cycle on this after merged and deploy to nvq2

2024-07-04 07:51 UTC, inbal-ben-david approved these changes

2024-07-08 15:13 UTC, merged